name: Build and Upload APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract ZIP file
        run: |
          unzip AngelArum_FakeGPS_final.zip

      - name: Navigate to directory
        run: |
          cd AngelArum_FakeGPS_final/GhostLocation

      - name: Build APK
        run: |
          cd AngelArum_FakeGPS_final/GhostLocation && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App APK
          path: AngelArum_FakeGPS_final/GhostLocation/app/build/outputs/apk/debug/app-debug.apk
